<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Dalamud.NET.Sdk/12.0.2">
  <PropertyGroup>
    <Description>Add bulk tags dynamically to penumbra mods based on conditions</Description>
    <PackageProjectUrl>https://github.com/anya-hichu/ModAutoTagger</PackageProjectUrl>
    <PackageLicenseExpression>AGPL-3.0-or-later</PackageLicenseExpression>
    <IsPackable>false</IsPackable>
    <TargetFramework>net9.0-windows7.0</TargetFramework>
  </PropertyGroup>
</Project>
